brig:
  host: 0.0.0.0
  port: 8082

cassandra:
  endpoint:
    host: 127.0.0.1
    port: 9042
  keyspace: brig_test

elasticsearch:
  url: http://127.0.0.1:9200
  index: directory_test

cargohold:
  host: 127.0.0.1
  port: 8084

galley:
  host: 127.0.0.1
  port: 8085

gundeck:
  host: 127.0.0.1
  port: 8086

aws:
  blacklistTable: integration-brig-userkey-blacklist
  prekeyTable: integration-brig-prekeys
  internalQueue: integration-brig-events-internal
  sqsEndpoint: http://localhost:4568 # https://sqs.eu-west-1.amazonaws.com
  dynamoDBEndpoint: http://localhost:4567 # https://dynamodb.eu-west-1.amazonaws.com
emailSMS:
  email:
    sesQueue: integration-brig-events
    sesEndpoint: http://localhost:4569 # https://email.eu-west-1.amazonaws.com
  general:
    templateDir: resources/templates
    emailSender: backend-integration@wire.com
    smsSender: "<insert-sender-number-here>"

  user:
    activationUrl: http://127.0.0.1:8080/activate?key=${key}&code=${code}
    smsActivationUrl: http://127.0.0.1:8080/v/${code}
    passwordResetUrl: http://127.0.0.1:8080/password-reset/${key}?code=${code}
    invitationUrl: http://127.0.0.1:8080/register?invitation_code=${code}
    deletionUrl: http://127.0.0.1:8080/users/delete?key=${key}&code=${code}

  provider:
    homeUrl: https://provider.localhost/
    providerActivationUrl: http://127.0.0.1:8080/provider/activate?key=${key}&code=${code}
    approvalUrl: http://127.0.0.1:8080/provider/approve?key=${key}&code=${code}
    approvalTo: success@simulator.amazonses.com
    providerPwResetUrl: http://127.0.0.1:8080/provider/password-reset?key=${key}&code=${code}

  team:
    tInvitationUrl: http://127.0.0.1:8080/register?team=${team}&team_code=${code}
    tActivationUrl: http://127.0.0.1:8080/register?team=${team}&team_code=${code}
    tCreatorWelcomeUrl: http://127.0.0.1:8080/creator-welcome-website
    tMemberWelcomeUrl: http://127.0.0.1:8080/member-welcome-website

zauth:
  privateKeys: resources/zauth/privkeys.txt
  publicKeys: resources/zauth/pubkeys.txt
  authSettings:
    keyIndex: 1
    userTokenTimeout: 4838400    # 56 days
    sessionTokenTimeout: 604800  # 7 days
    accessTokenTimeout: 900      # 15 minutes
    providerTokenTimeout: 604800 # 7 days

turn:
  serversV2: resources/turn/servers-v2.txt
  servers: resources/turn/servers.txt
  secret: resources/turn/secret.txt
  # ^ TODO: This secret should be the same used by the TURN servers
  configTTL: 3600
  tokenTTL: 21600

optSettings:
  setTwilio: resources/twilio-credentials.yaml
  setNexmo: resources/nexmo-credentials.yaml
  setActivationTimeout: 1209600     # 1 day
  setTeamInvitationTimeout: 1814400 # 21 days
  setUserMaxConnections: 1000
  setCookieDomain: 127.0.0.1
  setCookieInsecure: false
  setUserCookieRenewAge: 1209600 # 14 days
  setUserCookieLimit: 32
  setUserCookieThrottle:
    stdDev: 3000      # 50 minutes
    retryAfter: 86400 # 1 day
  setDefaultLocale: en
  setMaxConvAndTeamSize: 128
