saml:
  version:   SAML2.0
  logLevel:  Debug

  spHost:    127.0.0.1
  spPort:    8088
  spAppUri:  http://localhost:8080/ # <--- change this to point to a reachable web app
  spSsoUri:  http://localhost:8080/sso # <--- change this to the URL by which spar can be reached from an external IdP

  contacts:
    - type: ContactBilling
      company: Example Company
      givenName: Example
      surname: Company
      email: email:company@example.com

brig:
  host: 127.0.0.1
  port: 8082

galley:
  host: 127.0.0.1
  port: 8085

cassandra:
  endpoint:
    host: 127.0.0.1
    port: 9042
  keyspace: spar_test

maxttlAuthreq: 28800 # 8h
maxttlAuthresp: 28800 # 8h

maxScimTokens: 16    # Token limit {#RefScimToken}
richInfoLimit: 5000  # should be in sync with Brig

logNetStrings: False # log using netstrings encoding (see http://cr.yp.to/proto/netstrings.txt)
