saml:
  version:   SAML2.0
  logLevel:  Debug

  spHost:    127.0.0.1
  spPort:    8088
  spAppUri:  http://localhost:8080/ # <--- change this to point to a reachable web app
  spSsoUri:  http://localhost:8080/

  contacts:
    - type: ContactBilling
      company: Example Company
      givenName: Example
      surname: Company
      email: email:company@example.com

brig:
  host: 127.0.0.1
  port: 8082

galley:
  host: 127.0.0.1
  port: 8085

cassandra:
  endpoint:
    host: 127.0.0.1
    port: 9042
  keyspace: spar_test

maxttlAuthreq: 28800 # 8h
maxttlAuthresp: 28800 # 8h

maxScimTokens: 16

logNetStrings: False # log using netstrings encoding (see http://cr.yp.to/proto/netstrings.txt)

spInfo:
  metaURI:  http://localhost:8088/sso/metadata
  loginURI: http://localhost:8088/sso/initiate-login/
