gundeck:
  host: 0.0.0.0
  port: 8080

brig:
  host: brig-federation-v1
  port: 8080

cassandra:
  endpoint:
    host: demo_wire_cassandra
    port: 9042
  keyspace: gundeck_test_federation_v1
  # filterNodesByDatacentre: datacenter1

redis:
  host: redis-federation-v1
  port: 6379
  connectionMode: master

# redisAdditionalWrite:
#   host: 127.0.0.1
#   port: 6379
#   connectionMode: master

aws:
  queueName: integration-gundeck-events-federation-v1
  region: eu-west-1
  account: "123456789012" # Default account nr used by localstack
  arnEnv: integration
  sqsEndpoint: http://demo_wire_sqs:4568 # https://sqs.eu-west-1.amazonaws.com
  snsEndpoint: http://demo_wire_sns:4575 # https://sns.eu-west-1.amazonaws.com

settings:
  httpPoolSize: 1024
  notificationTTL: 24192200
  bulkPush: true
  perNativePushConcurrency: 32
  sqsThrottleMillis: 1000
  maxConcurrentNativePushes:
    hard: 30  # more than this number of threads will not be allowed
    soft: 10  # more than this number of threads will be warned about
  disabledAPIVersions: []

logLevel: Warn
logNetStrings: false
