version: '2'
services:
  fake_dynamodb:
    image: cnadiminti/dynamodb-local:2017-02-16
    ports:
      - 4567:8000

  fake_sqs:
    image: airdock/fake-sqs:0.3.1
    ports:
      - 4568:4568

  fake_localstack:
    image: localstack/localstack:0.8.5
    ports:
      - 4569:4579 # ses
      - 4575:4575 # sns
    environment:
      - DEBUG=1
      - DEFAULT_REGION=eu-west-1
      - SERVICES=ses,sns

  fake_s3:
      image: tiagoloureiro/fake-s3:0.2.5
      ports:
        - 4570:4570

  redis:
    image: redis:3.0.7-alpine
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  cassandra:
    image: cassandra:3.11.1
    ports:
      - "9042:9042"

  db_migrations:
    image: wireserver/migrations
    depends_on:
      - elasticsearch
      - cassandra
    command: /scripts/db-migrate.sh
    volumes:
      - ./:/scripts
    links:
      - elasticsearch
      - cassandra

  aws_cli:
    image: mesosphere/aws-cli:1.14.5
    depends_on:
      - fake_dynamodb
      - fake_sqs
      - fake_localstack
      - fake_s3
    links:
      - fake_dynamodb:dynamodb
      - fake_sqs:sqs
      - fake_localstack:ses
      - fake_localstack:sns
      - fake_s3:s3
    entrypoint: /scripts/aws-init.sh
    volumes:
      - ./:/scripts
