apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sftd.fullname" . }}
  labels:
    {{- include "sftd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  # Allows sfts to start up and shut down in parallel when scaling up and down.
  # However this does not affect upgrades.
  podManagementPolicy: Parallel
  serviceName: {{ include "sftd.fullname" . }}
  selector:
    matchLabels:
      {{- include "sftd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sftd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ include "sftd.fullname" . }}
      volumes:
        - name: external-ip
          emptyDir: {}
        - name: multi-sft-config
          emptyDir: {}
      initContainers:
        - name: get-external-ip
          image: bitnami/kubectl:1.19.7
          volumeMounts:
            - name: external-ip
              mountPath: /external-ip
          command:
            - /bin/sh
            - -c
            - |
              set -e

              # In the cloud, this setting is available to indicate the true IP address
              addr=$(kubectl get node $HOSTNAME -ojsonpath='{.status.addresses[?(@.type=="ExternalIP")].address}')

              # On on-prem we allow people to set  "wire.com/external-ip" to override this
              if [ -z "$addr" ]; then
                addr=$(kubectl get node $HOSTNAME -ojsonpath='{.metadata.annotations.wire\.com/external-ip}')
              fi
              echo -n "$addr" | tee /dev/stderr > /external-ip/ip
        - name: get-multi-sft-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          volumeMounts:
            - name: multi-sft-config
              mountPath: /multi-sft-config

          command:
            - /bin/sh
            - -c
            - |
              set -e

              {{- if .Values.multiSFT.enabled }}

              response=$(curl "{{ .Values.multiSFT.turnDiscoveryURL }}")
              if [ -z "$response" ]; then
                 echo "No response from restund server."
                 exit 1
              fi

              echo "$response" | jq -r '.username' > /multi-sft-config/username
              if [ ! -s /multi-sft-config/username ]; then
                echo "Response does not contain a username"
                exit 1
              fi

              echo "$response" | jq -r '.password' > /multi-sft-config/password
              if [ ! -s /multi-sft-config/password ]; then
                echo "Response does not contain a password"
                exit 1
              fi

              echo "$response" | jq -r '.uris[0]' > /multi-sft-config/turn_server
              if [ ! -s /multi-sft-config/turn_server ]; then
                echo "Response does not contain a turn server"
                exit 1
              fi

              {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: external-ip
              mountPath: /external-ip
            - name: multi-sft-config
              mountPath: /multi-sft-config
          command:
            - /bin/sh
            - -c
            - |
              set -e
              EXTERNAL_IP=$(cat /external-ip/ip)
              if [ -z "${EXTERNAL_IP}" ]; then
                ACCESS_ARGS=
              else
                ACCESS_ARGS="-A ${EXTERNAL_IP}"
              fi

              {{- if .Values.multiSFT.enabled }}
              MULTI_SFT_ARGS="-t \"$(cat /multi-sft-config/turn_server)\" \
              -x \"$(cat /multi-sft-config/username)\" \
              -c \"$(cat /multi-sft-config/password)\""
              {{- else }}
              MULTI_SFT_ARGS=""
              {{- end }}

              exec sftd \
                      -I "${POD_IP}" \
                      -M "${POD_IP}" \
                      ${ACCESS_ARGS} \
                      ${MULTI_SFT_ARGS} \
                      {{ if .Values.turnDiscoveryEnabled }}-T{{ end }} \
                      -u "https://{{ required "must specify host" .Values.host }}/sfts/${POD_NAME}"
          ports:
            - name: sft
              containerPort: 8585
              protocol: TCP
            - name: metrics
              containerPort: 49090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          lifecycle:
            preStop:
              exec:
                # TODO: Workaround because sftd does not support graceful draining natively.
                # tracked in https://github.com/zinfra/backend-issues/issues/1451
                command:
                  - /bin/sleep
                  - "{{ .Values.terminationGracePeriodSeconds }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
