saml:
  version:   SAML2.0
  logLevel:  Warn

  spHost:    0.0.0.0
  spPort:    8080
  # TODO: change these
  spAppUri:  http://localhost:8080/
  spSsoUri:  http://localhost:8080/sso

  contacts:
    - type: ContactBilling
      company: evil corp.
      givenName: Dr.
      surname: Girlfriend
      email: email:president@evil.corp

scimBaseUri: http://localhost:8088/scim/v2

brig:
  host: brig-federation-v2
  port: 8080

galley:
  host: galley-federation-v2
  port: 8080

cassandra:
  endpoint:
    host: demo_wire_cassandra
    port: 9042
  keyspace: spar_test_federation_v1
  filterNodesByDatacentre: datacenter1

# Wire/AWS specific, optional
# discoUrl: "https://"

disabledAPIVersions: []

maxttlAuthreq: 5  # seconds.  don't set this too large, it is also the run time of one TTL test.
maxttlAuthresp: 7200  # seconds.  do not set this to 1h or less, as that is what the mock idp wants.

maxScimTokens: 8     # Token limit {#RefScimToken}
richInfoLimit: 5000  # should be in sync with Brig

logNetStrings: False # log using netstrings encoding (see http://cr.yp.to/proto/netstrings.txt)
