apiVersion: v1
kind: Secret
metadata:
  name: openldap-newusers-ldif
  labels:
    wireService: ldap-scim-bridge
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  00-users.ldif: |
    dn: ou=People,dc=nodomain
    objectClass: organizationalUnit
    ou: People
  10-newusers.ldif: |
    dn: cn=john,ou=People,dc=nodomain
    objectClass: top
    objectClass: account
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: john
    uid: john
    uidNumber: 10001
    gidNumber: 10001
    homeDirectory: /home/john
    userPassword: notgonnatell
    loginShell: /bin/bash

    dn: cn=jane,ou=People,dc=nodomain
    objectClass: top
    objectClass: account
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: jane
    uid: jane
    uidNumber: 10002
    gidNumber: 10002
    homeDirectory: /home/jane
    userPassword: notgonnatelleither
    loginShell: /bin/bash

    dn: cn=me,ou=People,dc=nodomain
    objectClass: top
    objectClass: account
    objectClass: posixAccount
    objectClass: shadowAccount
    cn: me
    uid: me
    uidNumber: 10003
    gidNumber: 10003
    homeDirectory: /home/me
    userPassword: notgonnatelleither
    loginShell: /bin/bash

    dn: cn=usesemail,ou=People,dc=nodomain
    objectClass: top
    objectClass: account
    objectClass: posixAccount
    objectClass: shadowAccount
    objectClass: extensibleObject
    cn: usesemail
    uid: usesemail
    uidNumber: 10004
    gidNumber: 10004
    email: uses@example.com
    homeDirectory: /home/me
    userPassword: notgonnatelleither
    loginShell: /bin/bash
