{{- if and .Values.federator.enabled (not .Values.tls.enabled) }}
{{- fail "TLS is required by federator. Either disable federation or enable tls." }}
{{- end }}
{{- if and .Values.federator.enabled (and .Values.tls.enabled .Values.tls.useCertManager) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "federator-{{ include "nginx-ingress-services.zone" . | replace "." "-" }}-csr"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  issuerRef:
    name: {{ .Values.tls.issuer.name }}
    kind: {{ .Values.tls.issuer.kind }}
  usages:
    - server auth
    - client auth
  duration: 2160h     # 90d, Letsencrypt default; NOTE: changes are ignored by Letsencrypt
  renewBefore: 360h   # 15d
  isCA: false
  secretName: federator-certificate-secret
  privateKey:
    algorithm: ECDSA
    size: 256         # hs-tls only supports p256
    encoding: PKCS1
    rotationPolicy: Always
  dnsNames:
    - {{ .Values.config.dns.federator }}
{{- end -}}
