# FUTUREWORK: move services into the respective charts
{{- if not .Values.config.isAdditionalIngress }}
{{- if .Values.webapp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-http
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.webapp.externalPort }}
      targetPort: 8080
  selector:
    app: webapp
{{- end }}
{{- if .Values.service.useFakeS3 }}
---
apiVersion: v1
kind: Service
metadata:
  name: s3-http
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.s3.externalPort }}
      targetPort: 9000
  selector:
    app: {{ .Values.service.s3.serviceName }}
{{- end }}
{{- if .Values.teamSettings.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: team-settings-http
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.teamSettings.externalPort }}
      targetPort: 8080
  selector:
    app: team-settings
{{- end }}
{{- if .Values.accountPages.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: account-pages-http
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.accountPages.externalPort }}
      targetPort: 8080
  selector:
    app: account-pages
{{- end }}
{{- end }}
