# The amount of Restund instances to run.  NOTE: Only one Restund can run per node due
# to `hostNetwork`. If this number is higher than the amount of nodes that can
# be used for scheduling (Also see `nodeSelector`) pods will remain in a
# pending state untill you add more capacity.
replicaCount: 1

image:
  repository: quay.io/wire/restund
  pullPolicy: Always
  # overwrite the tag here, otherwise `appVersion` of the chart will be used
  tag: ""

kubectlImage:
  registry: registry.k8s.io
  repository: kubectl
  tag: v1.32.9

# If you have multiple deployments of Restund running in one cluster, it is
# important that they run on disjoint sets of nodes, you can use nodeSelector to enforce this
nodeSelector: {}

podSecurityContext:
  fsGroup: 31337

securityContext:
  # Pick a high number that is unlikely to conflict with the host
  # https://kubesec.io/basics/containers-securitycontext-runasuser/
  runAsUser: 31337

restundUDPListenPort: 3478
restundTCPListenPort: 3478
restundUDPStatusPort: 33000
restundHTTPStatusPort: 8080
restundMetricsListenPort: 8443

federate:
  enabled: false
  port: 9191

  dtls:
    enabled: true

    tls:
    # Example:
    #
    # tls:
    #   key: "-----BEGIN EC PRIVATE KEY----- ..." # (ascii blob) private key
    #   crt: "-----BEGIN CERTIFICATE----- ..." # (ascii blob) certificate
    #
    # OR (mutually exclusive)
    #
    # tls:
    #    issuerRef:
    #      name: letsencrypt-http01
    #
    #      # We can reference ClusterIssuers by changing the kind here.
    #      # The default value is Issuer (i.e. a locally namespaced Issuer)
    #      # kind: Issuer
    #      kind: Issuer
    #
    #      # This is optional since cert-manager will default to this value however
    #      # if you are using an external issuer, change this to that issuer group.
    #      group: cert-manager.io
    #
    #    # optional labels to attach to the cert-manager Certificate
    #    certificate:
    #      labels: ..
    #
    # host: # public hostname for which the certificate is created for.
    #
    ca: # list of trusted CA certificates (concatenated list of PEMs)
    # example:
    # ca: "-----BEGIN CERTIFICATE-----"
