redis-ephemeral:
  extraSecretRedisConfigs: redis-extra-config
  image:
    tag: "7.4.6"

extraSecretRedisConfigs: redis-extra-config

configTemplate: |
  # dont write rdb to emptyDir disk - epehemeral setup
  save ""
  {{- if .Values.auth.enabled }}
  requirepass {{ .Values.auth.password }}
  {{- end }}

auth:
  enabled: false
  # password: very-secure-redis-master-password
