redis-ephemeral:
  extraSecretRedisConfigs: redis-extra-config
  image:
    tag: "7.4.6"

  haMode:
    enabled: false

extraSecretRedisConfigs: redis-extra-config

configTemplate: |
  # dont write rdb to emptyDir disk - ephemeral setup
  save ""
  {{- if .Values.auth.enabled }}
  requirepass {{ .Values.auth.password }}
  {{- end }}

auth:
  enabled: false
  # password: very-secure-redis-master-password

tls:
  enabled: false
  # certificatesSecret: redis-certificate
  # certFilename: "tls.crt"
  # certKeyFilename: "tls.key"
  # certCAFilename: "ca.crt"
  # authClients: false
