_meta:
  type: "internalusers"
  config_version: 2

elastic:
  hash: "$2y$12$GRc68jkEX1m4uQpTVbwURu79xHxZ7vsbyEctOAADQwPjlhYS4LJVa"
  reserved: true
  description: "Wire User"
  backend_roles:
    - index_manager
